### ISSUE TITLE
concurrent map iteration and map write

### ISSUE THREAD

**Issue by tinygg** [mna/redisc#27]
error as belows:
```
fatal error: concurrent map iteration and map write

goroutine 244 [running]:
runtime.throw(0xd7b264, 0x26)
	C:/go/src/runtime/panic.go:617 +0x72 fp=0xc00024adb0 sp=0xc00024ad80 pc=0x42c262
runtime.mapiternext(0xc00024af58)
	C:/go/src/runtime/map.go:860 +0x597 fp=0xc00024ae38 sp=0xc00024adb0 pc=0x40ea67
runtime.mapiterinit(0xc3b460, 0xc000157ad0, 0xc00024af58)
	C:/go/src/runtime/map.go:850 +0x1c9 fp=0xc00024ae58 sp=0xc00024ae38 pc=0x40e3d9
github.com/mna/redisc.(*Cluster).refresh(0xc000414000, 0x1f01, 0xc000282300)
	E:/ivs_proj/go_default_path/pkg/mod/github.com/mna/redisc@v1.1.5/cluster.go:81 +0x1e7 fp=0xc00024afc8 sp=0xc00024ae58 pc=0x8f5727
runtime.goexit()
	C:/go/src/runtime/asm_amd64.s:1337 +0x1 fp=0xc00024afd0 sp=0xc00024afc8 pc=0x458a21
created by github.com/mna/redisc.(*Cluster).needsRefresh
	E:/ivs_proj/go_default_path/pkg/mod/github.com/mna/redisc@v1.1.5/cluster.go:154 +0xc9
```

**Comment by mna** [comment]
Hello,

Thanks a lot for this report! Unfortunately, I can't find the race with just this information - the test suite passes with the race detector, and from a glance at all the places where the `Cluster.masters` map is accessed, every place is protected with the Cluster's mutex.

Could you share how the Cluster is accessed when that error is triggered? My guess is that the stack trace you pasted is clipped to just the redisc-relevant parts and points to the "map iteration" side of the concurrent error, was there a distinct stack trace for where the map was concurrently written to? I know the race detector prints the two parts of the race, but I'm not sure if the concurrent map access error does this.

Anything more you could share about what triggers that error would be super useful (e.g. if it's from an open source project, a link to that project, otherwise a minimal example that triggers the error would be best but it could be tricky to reproduce).

Thanks,
Martin

**Comment by mna** [comment]
Ping, awaiting further details.
